# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frbit < Formula
  desc "Command-line interface for the fortrabbit public API"
  homepage "https://github.com/fortrabbit/frbit-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.1.0/frbit_macOS_Intel.tar.gz"
      sha256 "14edcdb62c5b077fffe634f4302fa1620352f8e9a74dd17e8bd0db1c2625735e"

      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.1.0/frbit_macOS_AppleSilicon.tar.gz"
      sha256 "e56b09f29fe8bda93d608715315893d3c6eaf7ecaee2ac769c37d3ada843c23f"

      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.1.0/frbit_linux_amd64.tar.gz"
      sha256 "e9d55f33686783b4bcb18ab2af584d688312c032401e3bedb3be1d6e3c1eaf1e"
      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.1.0/frbit_linux_arm64.tar.gz"
      sha256 "57bf90e77a60eb3d520043e139e27e3511f1a031cbb753a15f77acd0acce9781"
      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  test do
    system "#{bin}/frbit", "version"
  end
end
