# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frbit < Formula
  desc "Command-line interface for the fortrabbit public API"
  homepage "https://github.com/fortrabbit/frbit-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.3.0/frbit_macOS_Intel.tar.gz"
      sha256 "72ec66579cddd0183a930fdc0504fd4004a5bc0a2396ee3dccf4db854d25f2ac"

      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.3.0/frbit_macOS_AppleSilicon.tar.gz"
      sha256 "81f4a6516e27a3eca03bdfc4553b50f6e8db963aae174bdc91792beba0037036"

      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.3.0/frbit_linux_amd64.tar.gz"
      sha256 "ea767f12195cf60575d85f9f4ab0fe632391b5b2ee4421d364fea707abca8be8"
      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.3.0/frbit_linux_arm64.tar.gz"
      sha256 "ce992db7c2df6969d735037dece7f5292d34dd6a125e711bcb422bc9b65c7880"
      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  test do
    system "#{bin}/frbit", "version"
  end
end
