# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frbit < Formula
  desc "Command-line interface for the fortrabbit public API"
  homepage "https://github.com/fortrabbit/frbit-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.2.0/frbit_macOS_Intel.tar.gz"
      sha256 "674de15a9fa084d6ca6587be1b1dd1da0c968cff736f5812da09af26aff451c1"

      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.2.0/frbit_macOS_AppleSilicon.tar.gz"
      sha256 "582b66f8a664a1f92c3047bbdaf986be060a36004dd776098888ad174a16f7af"

      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.2.0/frbit_linux_amd64.tar.gz"
      sha256 "aa5a988c2ecf313b090470440e9133f30c628f53e19490d88959d6f8d913792b"
      define_method(:install) do
        bin.install "frbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fortrabbit/frbit-cli/releases/download/v1.2.0/frbit_linux_arm64.tar.gz"
      sha256 "3c3e179ad6079f01c61547fcb8c26280dc07bc1ff20f47c179f99c172f77d8f6"
      define_method(:install) do
        bin.install "frbit"
      end
    end
  end

  test do
    system "#{bin}/frbit", "version"
  end
end
